### PR TITLE
Fix network syncing issues

### PR DESCRIPTION
**Pull request by apaulb**

### CODE REVIEW

**Comment by ComputerCraftr** [comment]
So this reverts to the pnseed6 format and removes all the peer block requesting code?

**Comment by apaulb** [comment]
Changed to pnseed6 format to be compatible with the generate-seeds.py script. Just updated the seedlist with some of my masternodes. Should be populated with more seeders.

**Comment by apaulb** [comment]
The orphan problem seems to be related to this commit https://github.com/bitcoin/bitcoin/commit/f59d8f0b644d49324cabd19c58cf2262d49e1392

This commit should resolve it https://github.com/bitcoin/bitcoin/pull/4468

I can port all code up to Crave v2.1.0.3 later this week. But then we probably need to look into this problem

**Comment by ComputerCraftr** [comment]
That is fine, but this pull request is attempting to completely remove the improved block synchronization code and replace it with the original code instead of implementing the solution in the bitcoin pull request. For this reason, I don't think it would be wise to merge the pull request as it is now. I have also been using the following perl script to generate seed nodes in the new format:

```
my $ip;

if (@ARGV) {
    $ip = shift @ARGV;
} else {
    print "Enter an (dotted quad) ip address: ";
    chomp( $ip = <STDIN> );
}

printf "0x%08x\n",  unpack 'N', pack 'C4', reverse split '\.', $ip;
```

**Comment by apaulb** [comment]
I agree with you. Maybe port everything up to crave v2.1.0.3 excluding the v2.1.0.2 commit. Then look into porting the Bitcoin PR..

Btw most other repos seem to use the pnseed6 format. Including dash and Bitcoin. Might be a good idea to keep that one or update the generator.

**Pull request closed without merging**
